repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: ['--maxkb=1024']
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: detect-private-key

  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.1
    hooks:
      - id: go-fmt
      - id: go-imports
        args: ["-local", "github.com/zenglw/llm-gateway"]
      - id: go-mod-tidy
      - id: golangci-lint
        args: ["--config=.golangci.yml"]
      - id: go-unit-tests
        args: ["-race", "-run", "^Test.*$", "./..."]
